///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyRegisterBodyName = 'name';
const String _jsonKeyRegisterBodyPhone = 'phone';
const String _jsonKeyRegisterBodyEmail = 'email';
const String _jsonKeyRegisterBodyPassword = 'password';
class RegisterBody {
/*
{
  "name": "shimaa refaat",
  "phone": "011415281",
  "email": "alshimaa.refaat@ibm.com",
  "password": "123456"
}
*/

  String? name;
  String? phone;
  String? email;
  String? password;

  RegisterBody({
    this.name,
    this.phone,
    this.email,
    this.password,
  });
  RegisterBody.fromJson(Map<String, dynamic> json) {
    name = json[_jsonKeyRegisterBodyName]?.toString();
    phone = json[_jsonKeyRegisterBodyPhone]?.toString();
    email = json[_jsonKeyRegisterBodyEmail]?.toString();
    password = json[_jsonKeyRegisterBodyPassword]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyRegisterBodyName] = name;
    data[_jsonKeyRegisterBodyPhone] = phone;
    data[_jsonKeyRegisterBodyEmail] = email;
    data[_jsonKeyRegisterBodyPassword] = password;
    return data;
  }
}
